POST http://localhost:3000/auth/register
Content-Type: application/json

{
    "name": "naura",
    "email": "naura@mail.com",
    "password": "naura123"
}

###
POST http://localhost:3000/auth/login
Content-Type: application/json

{
    "email": "naura@mail.com",
    "password": "naura123"
}

