name: Deploy to GCR

on:
  push:
    branches:
      - "main"

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install NodeJS 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x

      - name: Install dependencies
        run: npm install

      - name: Build Docker image
        run: docker build -t my-express-app:latest .

      - name: Push Docker image to GCR
        run: gcloud docker push gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}/my-express-app:latest

      - name: Deploy to Cloud Run
        run: gcloud run deploy my-express-app --image gcr.io/${{ secrets.GOOGLE_PROJECT_ID }}//my-express-app:latest --platform managed

      - name: Check deployment status
        run: gcloud run services describe my-express-app